# Generated by Django 5.2.8 on 2025-12-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='users/avatars/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
